# Generated by Django 5.2.7 on 2025-10-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environment',
            old_name='light_on',
            new_name='light_blue',
        ),
        migrations.AddField(
            model_name='environment',
            name='last_rfid',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='environment',
            name='light_green',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='environment',
            name='light_red',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='environment',
            name='light_white',
            field=models.BooleanField(default=False),
        ),
    ]
