# Generated by Django 5.2.7 on 2025-11-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_light_on_environment_light_blue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='has_presence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='environment',
            name='people_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
